// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwQd-w6NzRQZs4To-TpYHpYsYNsHfz3bE',
    appId: '1:1074831686359:web:4eacdabaee6a7e7afb0e92',
    messagingSenderId: '1074831686359',
    projectId: 'datflixdb',
    authDomain: 'datflixdb.firebaseapp.com',
    storageBucket: 'datflixdb.firebasestorage.app',
    measurementId: 'G-FG1FN0HFVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrtH5DzKLmbAX3aDwLa7T-YoiGo8SsMPs',
    appId: '1:1074831686359:android:63e78aebea3a9051fb0e92',
    messagingSenderId: '1074831686359',
    projectId: 'datflixdb',
    storageBucket: 'datflixdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtY-JuQy4Y2_bkfHDjJB4TsNmRbbpXxGQ',
    appId: '1:1074831686359:ios:1132c8eb80453f13fb0e92',
    messagingSenderId: '1074831686359',
    projectId: 'datflixdb',
    storageBucket: 'datflixdb.firebasestorage.app',
    iosClientId: '1074831686359-pgcbmc2933n3jdcuvhn3f5l78fd34smv.apps.googleusercontent.com',
    iosBundleId: 'com.example.datflixFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtY-JuQy4Y2_bkfHDjJB4TsNmRbbpXxGQ',
    appId: '1:1074831686359:ios:1132c8eb80453f13fb0e92',
    messagingSenderId: '1074831686359',
    projectId: 'datflixdb',
    storageBucket: 'datflixdb.firebasestorage.app',
    iosClientId: '1074831686359-pgcbmc2933n3jdcuvhn3f5l78fd34smv.apps.googleusercontent.com',
    iosBundleId: 'com.example.datflixFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwQd-w6NzRQZs4To-TpYHpYsYNsHfz3bE',
    appId: '1:1074831686359:web:6b374328bd055046fb0e92',
    messagingSenderId: '1074831686359',
    projectId: 'datflixdb',
    authDomain: 'datflixdb.firebaseapp.com',
    storageBucket: 'datflixdb.firebasestorage.app',
    measurementId: 'G-9K4XSJ01TW',
  );
}
