name: datflix_frontend
description: A Flutter frontend for Datflix with Firebase and Kotlin backend integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # <-- Це обовʼязково
    sdk: flutter
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  firebase_core: ^2.13.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.0.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.3.2
  intl: ^0.20.2
  animated_text_kit: ^4.2.2
  video_player: ^2.5.1
  chewie: ^1.5.0
  google_fonts: ^4.0.3
  intl_utils: ^2.8.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/Icon.png"
  adaptive_icon_background: "#ffffff"
